version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  build:
    commands:
      - echo Build started on `date`
      - echo Running unit tests
      - phpunit --testsuite unit
  post_build:
    commands:
      - echo Build completed on `date`
