version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  build:
    commands:
      - echo Build started on `date`
      - echo Running unit tests
      - docker run --rm -v $(pwd)/example01:/app dcycle/phpunit:1 --group myproject
      - mkdir -p reports

  post_build:
    commands:
      - echo Build completed on `date`
      
reports:
  php-reports:
    files:
      - "*.xml"
    base-directory: "reports"
    file-format: "JUNITXML"

