version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Installing dependencies..."
      #- composer self-update
      #- composer require --dev phpunit/phpunit
      - mkdir -p reports
  pre_build:
    commands:
      - echo "Setting up test environment..."
      - php -v
      #- ./vendor/bin/phpunit --version
  build:
    commands:
      - echo "Running tests..."
      # Run with the new configuration
      #- ./vendor/bin/phpunit --configuration phpunit.xml --log-junit reports/junit.xml
      #- docker run --rm -v $(pwd)/example01:/app dcycle/phpunit:1 --group myproject
      - docker run --rm -v $(pwd)/example01:/app -v $(pwd)/reports:/reports dcycle/phpunit:1 tests/ --log-junit /reports/junit.xml --group myproject || echo "Tests failed but continuing build"
  post_build:
    commands:
      - echo "Build completed on `date`"
      - ls -la reports/

reports:
  php-reports:
    files:
      - "junit.xml"
    base-directory: "reports"
    file-format: "JUNITXML"
