version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Installing dependencies..."
      - composer self-update
      - composer require --dev phpunit/phpunit
      - mkdir -p reports
  pre_build:
    commands:
      - echo "Setting up test environment..."
      - php -v
      - ./vendor/bin/phpunit --version
  build:
    commands:
      - echo "Running tests..."
      # First try running without a specific test suite
      - ./vendor/bin/phpunit --debug || echo "Default PHPUnit run failed"
      # Run with the new configuration
      - ./vendor/bin/phpunit --configuration phpunit.xml --log-junit reports/junit.xml
  post_build:
    commands:
      - echo "Build completed on `date`"
      - ls -la reports/

reports:
  php-reports:
    files:
      - "junit.xml"
    base-directory: "reports"
    file-format: "JUNITXML"
