version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  build:
    commands:
      - composer install
      - echo Build started on `date`
      - echo Running unit tests
      - mkdir -p reports
      - phpunit --testsuite unit reports/junit.xml
   

  post_build:
    commands:
      - echo Build completed on `date`
      
reports:
  php-reports:
    files:
      - "*.xml"
    base-directory: "reports"
    file-format: "XML"

