version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  build:
    commands:
      - echo Build started on `date`
      - echo Running unit tests
      - docker run --rm -v $(pwd)/example01:/app/dcycle/phpunit:1 --group myproject
  post_build:
    commands:
      - echo Build completed on `date`
