version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - composer require --dev phpunit/phpunit
      - mkdir -p reports
  build:
    commands:
      - echo Build started on `date`
      - echo "Project structure:"
      - echo "PHPUnit version:"
      - ./vendor/bin/phpunit --version
      - echo "Trying to run with myproject test suite:"
      - ./vendor/bin/phpunit --debug --testsuite myproject --log-junit reports/junit.xml 
      
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -l reports

reports:
  php-reports:
    files:
      - "junit.xml"
    base-directory: "reports"
    file-format: "JUNITXML"
