version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  build:
    commands:
      - composer require --dev phpunit/phpunit
      - echo Build started on `date`
      - echo Running unit tests
      - mkdir -p reports
      - ./vendor/bin/phpunit --testsuite unit --log-junit reports/junit.xml
   
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -la reports/
      
reports:
  php-reports:
    files:
      - "junit.xml"
    base-directory: "reports"
    file-format: "JUNITXML"

